// Generated by scripts/gen-cli-registry.mjs. Do not edit by hand.
// 表里只有本仓真的存在、且真的带 bin 与 ./cli ./help 两条导出的节点包；
// 上游那份 46 条的清单里，没有对应物的条目一律不进（见本文件脚本头的说明）。

export const GENERATED_NODE_CLI_REGISTRY = [
  {
    id: "bandia",
    packageName: "@hibernalglow/xaihi-bandia",
    bin: "bandia",
    description: "Batch extract, compress, repack, and export archive paths with Bandizip.",
  },
  {
    id: "bitv",
    packageName: "@hibernalglow/xaihi-bitv",
    bin: "bitv",
    description: "Analyze video bitrate with ffprobe and classify files safely.",
  },
  {
    id: "classf",
    packageName: "@hibernalglow/xaihi-classf",
    bin: "classf",
    description: "Classify detected files into already, del, or wait without losing path context.",
  },
  {
    id: "classq",
    packageName: "@hibernalglow/xaihi-classq",
    bin: "classq",
    description: "Find keyword folders and move sibling items into wait folders.",
  },
  {
    id: "cleanf",
    packageName: "@hibernalglow/xaihi-cleanf",
    bin: "cleanf",
    description: "Preview and remove empty folders, backup files, temp folders, trash files, and cleanup presets.",
  },
  {
    id: "crashu",
    packageName: "@hibernalglow/xaihi-crashu",
    bin: "crashu",
    description: "Match similar folder names and optionally move matched folders.",
  },
  {
    id: "dissolvef",
    packageName: "@hibernalglow/xaihi-dissolvef",
    bin: "dissolvef",
    description: "Dissolve subfolders of a directory up one level using nested / media / archive / direct strategies. Plan first, then apply, with an undo journal.",
  },
  {
    id: "encodeb",
    packageName: "@hibernalglow/xaihi-encodeb",
    bin: "encodeb",
    description: "Preview and recover garbled filenames by re-decoding path components.",
  },
  {
    id: "enginev",
    packageName: "@hibernalglow/xaihi-enginev",
    bin: "enginev",
    description: "Scan, filter, rename, delete, and export Wallpaper Engine workshop folders.",
  },
  {
    id: "formatv",
    packageName: "@hibernalglow/xaihi-formatv",
    bin: "formatv",
    description: "Scan video folders, add/remove .nov suffixes, and check prefixed duplicates.",
  },
  {
    id: "gifu",
    packageName: "@hibernalglow/xaihi-gifu",
    bin: "gifu",
    description: "Convert image archives to GIF, WebP, APNG, WebM, or MP4 with the native media runtime.",
  },
  {
    id: "linedup",
    packageName: "@hibernalglow/xaihi-linedup",
    bin: "linedup",
    description: "Deduplicate multiline text and drop lines matching filters, returning kept and removed sets with counts.",
  },
  {
    id: "linku",
    packageName: "@hibernalglow/xaihi-linku",
    bin: "linku",
    description: "Create, move, import, restore, list, and recover symlink records.",
  },
  {
    id: "marku",
    packageName: "@hibernalglow/xaihi-marku",
    bin: "marku",
    description: "Run Markdown cleanup and conversion modules with preview diff.",
  },
  {
    id: "migratef",
    packageName: "@hibernalglow/xaihi-migratef",
    bin: "migratef",
    description: "Move or copy files with preserve, flat, and direct modes plus undo history.",
  },
  {
    id: "mvz",
    packageName: "@hibernalglow/xaihi-mvz",
    bin: "mvz",
    description: "Delete, extract, move, or rename files inside archives from findz output.",
  },
  {
    id: "nameu",
    packageName: "@hibernalglow/xaihi-nameu",
    bin: "nameu",
    description: "Preview and apply archive filename cleanup for artist folders.",
  },
  {
    id: "rawfilter",
    packageName: "@hibernalglow/xaihi-rawfilter",
    bin: "rawfilter",
    description: "Group similar archives and move duplicate/raw versions to trash or multi.",
  },
  {
    id: "recycleu",
    packageName: "@hibernalglow/xaihi-recycleu",
    bin: "recycleu",
    description: "Empty the Windows recycle bin immediately or on a bounded timer.",
  },
  {
    id: "repacku",
    packageName: "@hibernalglow/xaihi-repacku",
    bin: "repacku",
    description: "Analyze folder structures and repack matching folders into zip archives.",
  },
  {
    id: "samea",
    packageName: "@hibernalglow/xaihi-samea",
    bin: "samea",
    description: "Extract artist metadata from archive names and organize matching archives.",
  },
  {
    id: "sleept",
    packageName: "@hibernalglow/xaihi-sleept",
    bin: "sleept",
    description: "Read sleep/hibernate settings and which processes hold sleep off, temporarily prevent system sleep, or put the machine to sleep now (hibernate on Windows). Covers macOS and Windows only.",
  },
  {
    id: "smartzip",
    packageName: "@hibernalglow/xaihi-smartzip",
    bin: "smartzip",
    description: "TypeScript archive workflows with automatic 7-Zip discovery.",
  },
  {
    id: "timeu",
    packageName: "@hibernalglow/xaihi-timeu",
    bin: "timeu",
    description: "Back up and restore file timestamps from JSON records.",
  },
  {
    id: "trename",
    packageName: "@hibernalglow/xaihi-trename",
    bin: "trename",
    description: "Scan folders into rename JSON, validate translated targets, rename, and undo.",
  },
]
