// Generated by scripts/gen-cli-registry.mjs. Do not edit by hand.
// 表里只有本仓真的存在、且真的带 bin 与 ./cli ./help 两条导出的节点包；
// 上游那份 46 条的清单里，没有对应物的条目一律不进（见本文件脚本头的说明）。

export const GENERATED_NODE_CLI_REGISTRY = [
  {
    id: "classf",
    packageName: "@hibernalglow/xaihi-classf",
    bin: "xclassf",
    description: "ClassF (scaffold initial definition)",
  },
  {
    id: "classq",
    packageName: "@hibernalglow/xaihi-classq",
    bin: "xclassq",
    description: "Find keyword folders and move sibling items into wait folders.",
  },
  {
    id: "cleanf",
    packageName: "@hibernalglow/xaihi-cleanf",
    bin: "xcleanf",
    description: "Cleanf (scaffold initial definition)",
  },
  {
    id: "crashu",
    packageName: "@hibernalglow/xaihi-crashu",
    bin: "xcrashu",
    description: "Match similar folder names and optionally move matched folders.",
  },
  {
    id: "dissolvef",
    packageName: "@hibernalglow/xaihi-dissolvef",
    bin: "xdissolvef",
    description: "Dissolve subfolders of a directory up one level using nested / media / archive / direct strategies. Plan first, then apply, with an undo journal.",
  },
  {
    id: "encodeb",
    packageName: "@hibernalglow/xaihi-encodeb",
    bin: "xencodeb",
    description: "Preview and recover garbled filenames by re-decoding path components.",
  },
  {
    id: "formatv",
    packageName: "@hibernalglow/xaihi-formatv",
    bin: "xformatv",
    description: "Scan video folders, add/remove .nov suffixes, and check prefixed duplicates.",
  },
  {
    id: "linedup",
    packageName: "@hibernalglow/xaihi-linedup",
    bin: "xlinedup",
    description: "Deduplicate multiline text and drop lines matching filters, returning kept and removed sets with counts.",
  },
  {
    id: "linku",
    packageName: "@hibernalglow/xaihi-linku",
    bin: "xlinku",
    description: "Create, move, import, restore, list, and recover symlink records.",
  },
  {
    id: "logx",
    packageName: "@hibernalglow/xaihi-logx",
    bin: "xlogx",
    description: "Analyze Xaihi structured logs across GUI, CLI, and OpenTUI.",
  },
  {
    id: "marku",
    packageName: "@hibernalglow/xaihi-marku",
    bin: "xmarku",
    description: "Run Markdown cleanup and conversion modules with preview diff.",
  },
  {
    id: "migratef",
    packageName: "@hibernalglow/xaihi-migratef",
    bin: "xmigratef",
    description: "Move or copy files with preserve, flat, and direct modes plus undo history.",
  },
  {
    id: "mvz",
    packageName: "@hibernalglow/xaihi-mvz",
    bin: "xmvz",
    description: "MVZ (scaffold initial definition)",
  },
  {
    id: "nameu",
    packageName: "@hibernalglow/xaihi-nameu",
    bin: "xnameu",
    description: "Preview and apply archive filename cleanup for artist folders.",
  },
  {
    id: "rawfilter",
    packageName: "@hibernalglow/xaihi-rawfilter",
    bin: "xrawfilter",
    description: "Group similar archives and move duplicate/raw versions to trash or multi.",
  },
  {
    id: "recycleu",
    packageName: "@hibernalglow/xaihi-recycleu",
    bin: "xrecycleu",
    description: "Empty the Windows recycle bin immediately or on a bounded timer.",
  },
  {
    id: "samea",
    packageName: "@hibernalglow/xaihi-samea",
    bin: "xsamea",
    description: "Extract artist metadata from archive names and organize matching archives.",
  },
  {
    id: "sleept",
    packageName: "@hibernalglow/xaihi-sleept",
    bin: "xsleept",
    description: "Read sleep/hibernate settings and which processes hold sleep off, temporarily prevent system sleep, or put the machine to sleep now (hibernate on Windows). Covers macOS and Windows only.",
  },
  {
    id: "smartzip",
    packageName: "@hibernalglow/xaihi-smartzip",
    bin: "xsmartzip",
    description: "SmartZip (scaffold initial definition)",
  },
  {
    id: "timeu",
    packageName: "@hibernalglow/xaihi-timeu",
    bin: "xtimeu",
    description: "Back up and restore file timestamps from JSON records.",
  },
  {
    id: "trename",
    packageName: "@hibernalglow/xaihi-trename",
    bin: "xtrename",
    description: "Scan folders into rename JSON, validate translated targets, rename, and undo.",
  },
]
